# Multiple Linear Regression

In [68]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
print(f'pandas  version: {pd.__version__}')
print(f'numpy   version: {np.__version__}')
print(f'seaborn version: {sns.__version__}')

pandas  version: 2.2.3
numpy   version: 2.0.1
seaborn version: 0.13.2


In [69]:
# url='http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv'
url='https://github.com/prasertcbs/basic-dataset/raw/master/ISLR/Advertising.csv'
# df=pd.read_csv(url, index_col=0)
df=pd.read_csv(url, usecols=[1, 2, 3, 4])
# df=pd.read_csv(url, usecols=list(range(1, 5)))
df.head()

,TV,Radio,Newspaper,Sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9


In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


## sklearn: LinearRegression

In [71]:
import sklearn
from sklearn.linear_model import LinearRegression
print(f'sklearn version: {sklearn.__version__}')

sklearn version: 1.7.0


In [72]:
model = LinearRegression()
model.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'positive': False,
 'tol': 1e-06}

In [73]:
len(df)

200

In [74]:
df.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [75]:
X = df.drop(columns=['Sales'])
y = df['Sales']

X_train = df.drop(columns=['Sales'])[:140]
y_train = df['Sales'][:140]

X_test = df.drop(columns=['Sales'])[140:]
y_test = df['Sales'][140:]
X_test.head()

,TV,Radio,Newspaper
140,73.4,17.0,12.9
141,193.7,35.4,75.6
142,220.5,33.2,37.9
143,104.6,5.7,34.4
144,96.2,14.8,38.9


In [76]:
len(X)

200

In [77]:
X.head()

,TV,Radio,Newspaper
0,230.1,37.8,69.2
1,44.5,39.3,45.1
2,17.2,45.9,69.3
3,151.5,41.3,58.5
4,180.8,10.8,58.4


In [78]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
X=df.drop(columns=['Sales'])
y=df['Sales']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [81]:
model.fit(X_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [82]:
model.score(X_test, y_test) # R-squared

0.8835902877609378

In [83]:
model.intercept_

np.float64(3.1003799411764312)

In [84]:
X.head(3)

,TV,Radio,Newspaper
0,230.1,37.8,69.2
1,44.5,39.3,45.1
2,17.2,45.9,69.3


In [85]:
model.coef_

array([0.04661253, 0.16920487, 0.00490988])

In [86]:
model.predict([[200, 40, 70]])

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([19.53477335])

In [87]:
model.predict([[200, 40, 70],
               [100, 80, 50],
               [ 40, 20, 10]])

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([19.53477335, 21.54351727,  8.39807758])

In [88]:
X_test.head()

,TV,Radio,Newspaper
123,123.1,34.6,12.4
49,66.9,11.7,36.8
194,149.7,35.6,6.0
173,168.4,7.1,12.8
161,85.7,35.8,49.3


In [89]:
y_hat=model.predict(X_test)
y_hat

array([14.75375403,  8.3791391 , 16.13142907, 12.21413175, 13.3946657 ,
       20.91032384, 19.88859116, 16.04277487, 17.41676392, 14.1041814 ,
       20.49391949, 15.08565787, 17.66903748, 14.33345568, 15.16543854,
        5.28225418, 21.67587161, 15.54187036, 16.98460172, 12.93719444,
       23.19163136, 18.86623941, 12.78190254, 12.52250222, 18.17731826,
        9.92372966, 20.43760681, 17.43756815, 16.60918773, 15.02267364,
       23.75133339, 18.80167897, 15.5699609 , 14.78087835,  8.36015456,
       20.26417762, 14.43910053,  8.74191639, 21.326427  , 14.83365907,
       12.77924467, 20.03323508, 21.3955619 , 20.76762002, 12.14826836,
       15.41702697, 10.25018889, 16.40852319, 10.52895203, 20.56163199,
        7.28167582, 13.71496901,  6.64955297,  9.7994871 ,  8.12056132,
       12.09705738, 17.23020702, 15.15298019, 19.58383657, 16.59514729])

In [90]:
dc=pd.concat([df[140:].reset_index(), pd.Series(y_hat, name='predicted')], axis='columns')
dc

,index,TV,Radio,Newspaper,Sales,predicted
0,140,73.4,17.0,12.9,10.9,14.753754
1,141,193.7,35.4,75.6,19.2,8.379139
2,142,220.5,33.2,37.9,20.1,16.131429
3,143,104.6,5.7,34.4,10.4,12.214132
4,144,96.2,14.8,38.9,11.4,13.394666
5,145,140.3,1.9,9.0,10.3,20.910324
6,146,240.1,7.3,8.7,13.2,19.888591
7,147,243.2,49.0,44.3,25.4,16.042775
8,148,38.0,40.3,11.9,10.9,17.416764
9,149,44.7,25.8,20.6,10.1,14.104181


## Statsmodels: Multiple Linear regression

In [91]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [92]:
# formula: response ~ predictor1 + predictor2
model_a = smf.ols(formula='Sales ~ TV + Radio + Newspaper', data=df[:140]).fit()
# model_a = smf.ols(formula='Sales ~ TV + Radio', data=df).fit()

In [93]:
print(model_a.summary())

                            OLS Regression Results                            
Dep. Variable:                  Sales   R-squared:                       0.894
Model:                            OLS   Adj. R-squared:                  0.891
Method:                 Least Squares   F-statistic:                     381.2
Date:                Wed, 09 Jul 2025   Prob (F-statistic):           5.60e-66
Time:                        12:02:36   Log-Likelihood:                -273.89
No. Observations:                 140   AIC:                             555.8
Df Residuals:                     136   BIC:                             567.5
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.0451      0.391      7.782      0.0

In [94]:
model_a.params # coef

Intercept    3.045142
TV           0.047049
Radio        0.179683
Newspaper   -0.003006
dtype: float64

In [95]:
model_a.pvalues

Intercept    1.608608e-12
TV           1.091697e-57
Radio        1.161068e-34
Newspaper    6.689820e-01
dtype: float64

In [96]:
model.intercept_ # sklearn

np.float64(3.1003799411764312)

In [97]:
model.coef_ # sklearn

array([0.04661253, 0.16920487, 0.00490988])

In [98]:
# ya_hat=model_a.predict(df.drop(columns=['Sales'])[140:])
ya_hat=model_a.predict(X_test)

In [99]:
ya_hat.head()

123    15.016597
49      8.184385
194    16.467011
173    12.205418
161    13.361691
dtype: float64

In [100]:
y_hat[:5]

array([14.75375403,  8.3791391 , 16.13142907, 12.21413175, 13.3946657 ])